# Generated by Django 4.2.4 on 2024-02-26 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtoCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('price', models.CharField(max_length=150, null=True)),
                ('quantity', models.CharField(max_length=150, null=True)),
                ('status', models.CharField(max_length=150, null=True)),
                ('payment', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pgapp.registration')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
