# Generated by Django 4.2.4 on 2024-02-26 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0005_addtocart_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='pg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pgapp.add_pg_info'),
        ),
    ]
