# Generated by Django 4.2.4 on 2024-02-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0007_rename_pg_addtocart_pg_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='quantity',
        ),
    ]
