# Generated by Django 4.2.4 on 2024-02-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0008_remove_addtocart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg_info',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
