# Generated by Django 4.2.4 on 2024-02-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0009_add_pg_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg_info',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
