# Generated by Django 4.2.4 on 2024-02-29 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0010_add_pg_info_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_pg_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pgapp.registration'),
        ),
    ]
